//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iRemember
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int P_Id { get; set; }
        public string P_Firstname { get; set; }
        public string P_Vorname { get; set; }
        public byte[] P_Image { get; set; }
        public Nullable<int> P_G_Group { get; set; }
    
        public virtual Group Group { get; set; }
    }
}
